"""Product-review sentiment lexicons.

Extracted verbatim from the original Streamlit dashboard so the hybrid
VADER + rule engine keeps producing identical verdicts.
"""

NEGATIVE_PHRASES = [
    "waste of money",
    "waste money",
    "waste of time",
    "waste time",
    "not worth",
    "not worth the money",
    "do not buy",
    "do not purchase",
    "don't buy",
    "dont buy",
    "don't purchase",
    "dont purchase",
    "should not buy",
    "should not be bought",
    "shouldn't buy",
    "shouldn't be bought",
    "avoid this",
    "avoid this product",
    "stay away",
    "never buy",
    "never purchase",
    "poor quality",
    "terrible quality",
    "bad quality",
    "low quality",
    "very slow",
    "too slow",
    "extremely slow",
    "does not work",
    "doesn't work",
    "doesnt work",
    "not working",
    "stopped working",
    "barely works",
    "hardly works",
    "broken",
    "broke",
    "defective",
    "useless",
    "disappointed",
    "disappointing",
    "disappointment",
    "horrible",
    "terrible",
    "awful",
    "worst",
    "worst product",
    "worst purchase",
    "bad product",
    "bad purchase",
    "poor product",
    "poor performance",
    "poor service",
    "poor design",
    "poor sound",
    "poor battery",
    "poor screen",
    "poor material",
    "too expensive",
    "overpriced",
    "not recommended",
    "would not recommend",
    "wouldn't recommend",
    "do not recommend",
    "not good",
    "not great",
    "not happy",
    "not satisfied",
    "very disappointing",
    "highly disappointing",
    "return this",
    "returned this",
    "sent it back",
    "send it back",
]

POSITIVE_PHRASES = [
    "highly recommend",
    "strongly recommend",
    "would recommend",
    "definitely recommend",
    "must buy",
    "great product",
    "excellent product",
    "excellent quality",
    "great quality",
    "good quality",
    "amazing quality",
    "fantastic quality",
    "works perfectly",
    "works great",
    "works well",
    "works perfectly well",
    "very good",
    "very great",
    "really good",
    "really great",
    "extremely good",
    "extremely great",
    "very happy",
    "very satisfied",
    "really happy",
    "really satisfied",
    "love this",
    "love the product",
    "love it",
    "excellent",
    "amazing",
    "fantastic",
    "awesome",
    "wonderful",
    "perfect",
    "best product",
    "best purchase",
    "worth the money",
    "worth every penny",
    "good value",
    "great value",
    "excellent value",
    "fast delivery",
    "quick delivery",
    "easy to use",
    "easy to install",
    "easy to setup",
    "high quality",
]

NEGATIVE_WORDS = [
    "bad",
    "terrible",
    "horrible",
    "awful",
    "worst",
    "poor",
    "broken",
    "useless",
    "defective",
    "disappointed",
    "disappointing",
    "slow",
    "expensive",
    "overpriced",
    "hate",
    "refund",
    "return",
    "problem",
    "problems",
    "failure",
    "fail",
    "failed",
    "damage",
    "damaged",
    "annoying",
    "waste",
]

POSITIVE_WORDS = [
    "good",
    "great",
    "excellent",
    "amazing",
    "awesome",
    "fantastic",
    "wonderful",
    "perfect",
    "love",
    "best",
    "happy",
    "satisfied",
    "recommend",
    "recommended",
    "easy",
    "quality",
    "fast",
    "useful",
    "value",
]

